spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: false
    database: H2
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false