server:
  port: 8081

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  jpa:
    show_sql: false
    database: H2
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false

 # RabbitMQ
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtualHost: "/"
  queues:
    email-verification-q: email-verification-queue
  exchanges:
    email-verification-ex: email-verification-exchange
    user-registration-ex: user-registration-exchange
  routing-keys:
    email-verification-rk: email-verification-key
    user-registration-rk: user-registration-key

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: 'info,health'

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    your.package.name: DEBUG
